### ISSUE TITLE
konstakang.com comprimised

### ISSUE THREAD

**Issue by PeterFrancoisBadenhorst** [KonstaT/android_device_zte_kis3#8]
Hey man, not sure how else to get into contact with you (i dont use twitter), but it seem konstakang.com has been comprimised
![image](https://github.com/user-attachments/assets/263683f6-cc43-4c3d-8245-29c849b4fb40)
that link is not pointing to your Androud host file, and seems to be downloading a 2.4mb file, which i think is malware

**Comment by KonstaT** [comment]
Nothing seems to be compromised at my site. I've provided a md5 checksum so that you can verify the file integrity yourself.

DLUpload is a free file hosting service and I assume that the ads/popup windows they show on their site seem to cause confusion for some people on how to find the right download button.
